Fix/change on tap in badges
yako-dev/flutter_badges pull request #69
Opened 2022-10-18 14:44 UTC by sawel24

## Connection with issue(s)

add onTap to badge without child widget,add widget tests for onTap badge

2022-10-24 06:46 UTC, sanjidbillah requested changes

2022-10-24 06:46 UTC, sanjidbillah commented on example/ios/Flutter/AppFrameworkInfo.plist
> -  <string>9.0</string>
Why did you change os version?

2022-10-24 06:46 UTC, sanjidbillah commented on example/ios/Runner.xcodeproj/project.pbxproj
> -				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
Why did you set target 9 to 11?

2022-10-30 10:24 UTC, yadaniyil approved these changes

2022-10-30 10:24 UTC, merged