feat: add duration of the appearance Badge
yako-dev/flutter_badges pull request #70
Opened 2022-10-31 12:46 UTC by sawel24

## Connection with issue(s)

Resolve issue #???

## Testing and Review Notes

<!-- Required: You need to create a Badge widget, set the appearanceDration, and check how long the Badge will animate before full appearance--

2022-11-02 21:57 UTC, yadaniyil commented
@sawel24 so you added new parameter, but used the old one? really?
<img width="550" alt="image" src="https://user-images.githubusercontent.com/16175106/199610210-1fc5a10d-f816-4b2c-a03f-68ced9cf9880.png">

2022-11-02 22:05 UTC, yadaniyil requested changes
Not working

2022-11-03 15:42 UTC, sawel24 commented
> Not working

I changed it and it should work now

2022-11-09 17:19 UTC, yadaniyil requested changes

2022-11-09 17:19 UTC, yadaniyil commented on lib/src/badge.dart
> +  /// Сontrols the duration of the appearance Badge.
```suggestion
  /// Duration of the badge appearance and disappearance animations.
  /// Set this to zero to skip the badge appearance and disappearance animations
```

2022-11-09 17:19 UTC, merged