feat: add loop of the animation badge
yako-dev/flutter_badges pull request #72
Opened 2022-10-31 17:23 UTC by sawel24

## Connection with issue(s)

Add a loop of the animation badge

Screen Recording 2022-10-31 at 19.17.49.mov

2022-11-01 09:23 UTC, yadaniyil commented
@sawel24 no one will use this type of loop animation. Can you show how fade in fade out looks like?

2022-11-02 10:07 UTC, sawel24 commented
> @sawel24 no one will use this type of loop animation. Can you show how fade in fade out looks like?
These are examples of looped fade animation and scale animation

https://user-images.githubusercontent.com/82770717/199462210-4d02a43e-31b0-490c-83f7-033cf81ec69a.mov


https://user-images.githubusercontent.com/82770717/199462283-8c13c3e4-2a00-4e50-a54f-c0ba61395651.mov

2022-11-02 10:33 UTC, yadaniyil commented on lib/src/badge.dart
> +  ///Controls loop of the animation
there have to be a blank space

2022-11-02 10:34 UTC, yadaniyil commented on lib/src/badge.dart
> +  /// /// See also:
why 6 slashes are used?

2022-11-02 11:34 UTC, sawel24 commented
New versions of the animation

https://user-images.githubusercontent.com/82770717/199479714-b3242f9d-d42c-463a-b2ae-9792ccbf37a8.mov

https://user-images.githubusercontent.com/82770717/199479624-87bb8f41-41f9-4e6c-a48c-2a43d6f909a7.mov

2022-11-02 11:38 UTC, yadaniyil commented
@sawel24 Good job! Can we try to add curves to our animations? They will look more real

2022-11-02 16:52 UTC, sawel24 commented
> @sawel24 Good job! Can we try to add curves to our animations? They will look more real

I added a variable to control our animation. These are one of the examples, animation with adding a curve 

https://user-images.githubusercontent.com/82770717/199551570-a93b25e1-144b-458e-a747-4c197f4e300c.mov

2022-11-02 22:01 UTC, yadaniyil commented
@sawel24 In this PR you are breaking the current animation behavior. You make Curve.easeIn the default curve, but you removed Curves.elasticOut for slide animation type. 
Also, think about creating a separate constructor for looped animation badge, e.g. Badge.looped(child:...)

2022-11-02 22:04 UTC, yadaniyil requested changes
Left a comment

2022-11-04 01:27 UTC, sawel24 commented
> @sawel24 In this PR you are breaking the current animation behavior. You make Curve.easeIn the default curve, but you removed Curves.elasticOut for slide animation type. Also, think about creating a separate constructor for looped animation badge, e.g. Badge.looped(child:...)

I fixed the broken animation for the slide and created a separate constructor for the looped Badge. Recheck the code, is this the right solution?

2022-11-15 12:57 UTC, yadaniyil approved these changes

2022-11-15 12:57 UTC, merged